import 'dart:io';
import 'dart:ui' as ui;

import 'package:csv/csv.dart';
import 'package:decimal/decimal.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../../ledger/models/expense_model.dart';
import '../../ledger/models/settlement_model.dart';
import '../../ledger/providers/expense_provider.dart';
import '../../logistics/models/sub_group_model.dart';
import '../models/trip_model.dart';

/// Service for exporting trip data to PDF and CSV formats
class TripExportService {
  /// Generate and share a PDF summary of the trip
  static Future<void> exportAndSharePDF({
    required Trip trip,
    required List<Expense> expenses,
    required List<Settlement> settlements,
    required List<Participant> participants,
    required List<SubGroup> subGroups,
  }) async {
    // Calculate balances
    final balances = BalanceCalculator.calculateBalances(
      expenses: expenses,
      settlements: settlements,
      participants: participants,
      subGroups: subGroups,
    );

    // Calculate outstanding settlements
    final Map<String, String> userNames = {
      for (var p in participants) p.id: p.displayName ?? 'Unknown',
    };
    final outstandingSettlements =
        BalanceCalculator.calculateOptimalSettlements(
          balances: balances,
          userNames: userNames,
        );

    // Generate PDF
    final pdf = pw.Document();
    final dateFormat = DateFormat('MMM d, yyyy');
    final now = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Header
          _buildHeader(trip, dateFormat),
          pw.SizedBox(height: 20),

          // Participants & Balances
          _buildParticipantsSection(participants, balances),
          pw.SizedBox(height: 20),

          // Outstanding Settlements (if any)
          if (outstandingSettlements.isNotEmpty) ...[
            _buildOutstandingSettlementsSection(outstandingSettlements),
            pw.SizedBox(height: 20),
          ],

          // Expenses Table
          _buildExpensesSection(expenses, userNames, dateFormat),
          pw.SizedBox(height: 20),

          // Completed Settlements
          if (settlements.isNotEmpty)
            _buildCompletedSettlementsSection(settlements, userNames),
        ],
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 20),
          child: pw.Text(
            'Generated by Safar on ${dateFormat.format(now)}',
            style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
          ),
        ),
      ),
    );

    // Save to temp file
    final output = await getTemporaryDirectory();
    final fileName = '${trip.name.replaceAll(' ', '_')}_summary.pdf';
    final file = File('${output.path}/$fileName');
    await file.writeAsBytes(await pdf.save());

    // Share (with position for iPad compatibility)
    await Share.shareXFiles(
      [XFile(file.path)],
      subject: '${trip.name} - Trip Summary',
      sharePositionOrigin: const ui.Rect.fromLTWH(0, 0, 100, 100),
    );
  }

  /// Generate and share a CSV export of expenses
  static Future<void> exportAndShareCSV({
    required Trip trip,
    required List<Expense> expenses,
    required List<Participant> participants,
  }) async {
    final Map<String, String> userNames = {
      for (var p in participants) p.id: p.displayName ?? 'Unknown',
    };
    final dateFormat = DateFormat('yyyy-MM-dd');

    // Build CSV data
    final List<List<dynamic>> rows = [
      // Header row
      ['Date', 'Description', 'Category', 'Amount (OMR)', 'Payer', 'Scope'],
    ];

    for (final expense in expenses) {
      rows.add([
        dateFormat.format(expense.createdAt),
        expense.description ?? expense.categoryName ?? 'Expense',
        expense.categoryName ?? '',
        expense.amount.toStringAsFixed(3),
        userNames[expense.payerParticipantId] ?? 'Unknown',
        expense.scope.name,
      ]);
    }

    // Convert to CSV string
    final csvString = const ListToCsvConverter().convert(rows);

    // Save to temp file
    final output = await getTemporaryDirectory();
    final fileName = '${trip.name.replaceAll(' ', '_')}_expenses.csv';
    final file = File('${output.path}/$fileName');
    await file.writeAsString(csvString);

    // Share (with position for iPad compatibility)
    await Share.shareXFiles(
      [XFile(file.path)],
      subject: '${trip.name} - Expenses',
      sharePositionOrigin: const ui.Rect.fromLTWH(0, 0, 100, 100),
    );
  }

  // ============================================
  // PDF Section Builders
  // ============================================

  static pw.Widget _buildHeader(Trip trip, DateFormat dateFormat) {
    final dateRange = trip.startDate != null
        ? '${dateFormat.format(trip.startDate!)}${trip.endDate != null ? ' - ${dateFormat.format(trip.endDate!)}' : ''}'
        : 'No dates set';

    return pw.Container(
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'TRIP SUMMARY',
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blue800,
              letterSpacing: 2,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            trip.name,
            style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            dateRange,
            style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Invite Code: ${trip.inviteCode}',
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blue600,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildParticipantsSection(
    List<Participant> participants,
    List<UserBalance> balances,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'PARTICIPANTS (${participants.length})',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 10),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(3),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(2),
            3: const pw.FlexColumnWidth(2),
          },
          children: [
            // Header
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey200),
              children: [
                _tableCell('Name', isHeader: true),
                _tableCell('Paid', isHeader: true),
                _tableCell('Owes', isHeader: true),
                _tableCell('Balance', isHeader: true),
              ],
            ),
            // Data rows
            ...balances.map((b) {
              final balanceColor = b.netBalance > Decimal.zero
                  ? PdfColors.green700
                  : b.netBalance < Decimal.zero
                  ? PdfColors.red700
                  : PdfColors.grey700;
              final balancePrefix = b.netBalance > Decimal.zero ? '+' : '';

              return pw.TableRow(
                children: [
                  _tableCell(b.displayName ?? 'Unknown'),
                  _tableCell(b.totalPaid.toStringAsFixed(3)),
                  _tableCell(b.totalOwed.toStringAsFixed(3)),
                  _tableCell(
                    '$balancePrefix${b.netBalance.toStringAsFixed(3)}',
                    textColor: balanceColor,
                    isBold: true,
                  ),
                ],
              );
            }),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildOutstandingSettlementsSection(
    List<Map<String, dynamic>> settlements,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: PdfColors.orange50,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: PdfColors.orange200),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            '⚠ OUTSTANDING SETTLEMENTS',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.orange800,
            ),
          ),
          pw.SizedBox(height: 10),
          ...settlements.map((s) {
            final from = s['fromUserName'] as String;
            final to = s['toUserName'] as String;
            final amount = (s['amount'] as Decimal).toStringAsFixed(3);
            return pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 4),
              child: pw.Row(
                children: [
                  pw.Container(
                    width: 8,
                    height: 8,
                    decoration: const pw.BoxDecoration(
                      color: PdfColors.orange400,
                      shape: pw.BoxShape.circle,
                    ),
                  ),
                  pw.SizedBox(width: 10),
                  pw.Expanded(
                    child: pw.Text(
                      '$from owes $to $amount OMR',
                      style: const pw.TextStyle(fontSize: 12),
                    ),
                  ),
                ],
              ),
            );
          }),
        ],
      ),
    );
  }

  static pw.Widget _buildExpensesSection(
    List<Expense> expenses,
    Map<String, String> userNames,
    DateFormat dateFormat,
  ) {
    // Calculate total
    Decimal total = Decimal.zero;
    for (final e in expenses) {
      total = total + e.amount;
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'EXPENSES (${expenses.length})',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(
              'Total: ${total.toStringAsFixed(3)} OMR',
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blue700,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 10),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(1.5),
            1: const pw.FlexColumnWidth(3),
            2: const pw.FlexColumnWidth(1.5),
            3: const pw.FlexColumnWidth(2),
          },
          children: [
            // Header
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey200),
              children: [
                _tableCell('Date', isHeader: true),
                _tableCell('Description', isHeader: true),
                _tableCell('Amount', isHeader: true),
                _tableCell('Payer', isHeader: true),
              ],
            ),
            // Data rows (limit to most recent 50 for PDF)
            ...expenses.take(50).map((e) {
              return pw.TableRow(
                children: [
                  _tableCell(DateFormat('MMM d').format(e.createdAt)),
                  _tableCell(e.description ?? e.categoryName ?? 'Expense'),
                  _tableCell(e.amount.toStringAsFixed(3)),
                  _tableCell(userNames[e.payerParticipantId] ?? 'Unknown'),
                ],
              );
            }),
          ],
        ),
        if (expenses.length > 50)
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 8),
            child: pw.Text(
              '... and ${expenses.length - 50} more expenses (see CSV for full list)',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          ),
      ],
    );
  }

  static pw.Widget _buildCompletedSettlementsSection(
    List<Settlement> settlements,
    Map<String, String> userNames,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'COMPLETED SETTLEMENTS (${settlements.length})',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 10),
        ...settlements.map((s) {
          final from = userNames[s.payerParticipantId] ?? 'Unknown';
          final to = userNames[s.recipientParticipantId] ?? 'Unknown';
          return pw.Padding(
            padding: const pw.EdgeInsets.symmetric(vertical: 4),
            child: pw.Row(
              children: [
                pw.Container(
                  width: 16,
                  height: 16,
                  decoration: const pw.BoxDecoration(
                    color: PdfColors.green100,
                    shape: pw.BoxShape.circle,
                  ),
                  child: pw.Center(
                    child: pw.Text(
                      '✓',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.green700,
                      ),
                    ),
                  ),
                ),
                pw.SizedBox(width: 10),
                pw.Expanded(
                  child: pw.Text(
                    '$from paid $to ${s.amount.toStringAsFixed(3)} OMR',
                    style: const pw.TextStyle(fontSize: 12),
                  ),
                ),
                pw.Text(
                  DateFormat('MMM d').format(s.settledAt),
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
            ),
          );
        }),
      ],
    );
  }

  static pw.Widget _tableCell(
    String text, {
    bool isHeader = false,
    PdfColor? textColor,
    bool isBold = false,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: isHeader ? 11 : 10,
          fontWeight: isHeader || isBold ? pw.FontWeight.bold : null,
          color: textColor,
        ),
      ),
    );
  }
}
